// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmvoqZOt-FkPVgzn01vDPVJ-X9QD_VylM',
    appId: '1:195187408806:web:3b95602a386e624f9f1967',
    messagingSenderId: '195187408806',
    projectId: 'flutter-3d263',
    authDomain: 'flutter-3d263.firebaseapp.com',
    databaseURL: 'https://flutter-3d263-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-3d263.appspot.com',
    measurementId: 'G-BRYF5BZXNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHs0m4XDD9LR9eTv7MsGTnUZyEY6XUnkU',
    appId: '1:195187408806:android:a432c754fdb445559f1967',
    messagingSenderId: '195187408806',
    projectId: 'flutter-3d263',
    databaseURL: 'https://flutter-3d263-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-3d263.appspot.com',
  );
}
